export type SlipScanErrorCode =
  | 'SLIP_OPENAI_UNREACHABLE'
  | 'SLIP_RATE_LIMITED_HOUSEHOLD'
  | 'SLIP_RATE_LIMITED_USER'
  | 'SLIP_UNREADABLE'
  | 'SLIP_CONSENT_MISSING'
  | 'SLIP_OFFLINE'
  | 'SLIP_PAYLOAD_TOO_LARGE'
  | 'SLIP_FORBIDDEN'
  | 'SLIP_UNREASONABLE_EXTRACTION'
  | 'SLIP_WIFI_REQUIRED'
  | 'SLIP_INVALID_FRAME_COUNT'
  | 'SLIP_DB_ERROR'
  | 'SLIP_PARTIAL_SAVE_FAILED';

export type SlipScanError = {
  code: SlipScanErrorCode;
  message: string;
};
